# Generated by Django 5.1.3 on 2024-11-16 15:49

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
        ('sitee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('balance', models.IntegerField()),
                ('limit', multiselectfield.db.fields.MultiSelectField(choices=[('SINGLE_LIMIT', 'Разовый лимит'), ('MONTHLY_LIMIT', 'Месячный лимит'), ('MIN_BALANCE_LIMIT', 'Минимальный балансовый лимит'), ('MAX_BALANCE_LIMIT', 'Максимальный балансовый лимит')], max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('PAID', 'Оплачен'), ('CLOSED', 'Закрыт')], max_length=64)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitee.site')),
            ],
        ),
    ]
