# Generated by Django 5.1.3 on 2024-11-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SINGLE_LIMIT', 'Разовый лимит'), ('MONTHLY_LIMIT', 'Месячный лимит'), ('MIN_BALANCE_LIMIT', 'Минимальный балансовый лимит'), ('MAX_BALANCE_LIMIT', 'Максимальный балансовый лимит')], max_length=64, unique=True)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='limit',
        ),
        migrations.AddField(
            model_name='payment',
            name='limits',
            field=models.ManyToManyField(related_name='payments', to='payment.limit'),
        ),
    ]
