# Generated by Django 5.1.3 on 2024-11-18 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_limits_limit_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limit',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='limits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payment.limit'),
        ),
    ]
