# Generated by Django 5.1.3 on 2024-11-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_limit_payment_payment_limits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='limits',
        ),
        migrations.AddField(
            model_name='payment',
            name='limits',
            field=models.ManyToManyField(related_name='payments', to='payment.limit'),
        ),
    ]
